module MultiTranslate
  module Languages
    AUTODETECT = 'auto'
    ARABIC = 'ar'
    ARANESE = 'oc_aran'
    BASQUE = 'eu'
    BRAZILIAN_PORTUGUESE = 'pt_BR'
    BULGARIAN = 'bg'
    CATALAN = 'ca'
    CHINESE = 'zh-CN'
    CROTATIAN= 'hr'
    CZECH = 'cs'
    DANISH = 'da'
    DUTCH = 'nl'
    ENGLISH = 'en'
    ESPERANTO = 'eo'
    FILIPINO = 'tl'
    FINNISH = 'fi'
    FRENCH = 'fr'
    GALICIAN = 'gl'
    GERMAN = 'de'
    GREEK = 'el'
    HEBREW = 'iw'
    HINDI = 'hi'
    INDONESIAN = 'id'
    ITALIAN = 'it'
    JAPANESE = 'ja'
    KOREAN = 'ko'
    LATVIAN = 'lv'
    LITHUANIAN = 'lt'
    NORWEGIAN = 'no'
    OCCITAN = 'oc'
    POLISH = 'pl'
    PORTUGUESE = 'pt'
    ROMANIAN = 'ro'
    RUSSIAN = 'ru'
    SERBIAN = 'sr'
    SLOVAK = 'sk'
    SLOVENIAN = 'sl'
    SPANISH = 'es'
    SWEDISH = 'sv'
    UKRAINIAN = 'uk'
    VIETNAMESE = 'vi'
    WELSH = 'cy'
  end
end
